### ISSUE TITLE
Individual Review Ticket-Week 1

### ISSUE THREAD

**Issue by Anirudh123nasty** [Anirudh123nasty/ARTri3#6]

**Comment by Anirudh123nasty** [comment]
- 5.3 Notes
- 5.4 Notes
- InfoDB Loops & Lists
- Fibonacci Loop
- Comments and Documentation in Code

**Comment by PrishaB** [comment]
Score: 3/3
Checks 11/11:
5.3 Notes -> 1
5.4 Notes -> 1
InfoDBList -> 1
For Loop -> 1
While Loop -> 1
Recursive Loop -> 1
Fibonacci -> 1
Documentation/Comments -> 1
Prints with result and stuff -> 4
