### ISSUE TITLE
Individual Review Ticket-Week 2

### ISSUE THREAD

**Issue by Anirudh123nasty** [Anirudh123nasty/ARTri3#8]

**Comment by Anirudh123nasty** [comment]
- [ ] Organize files, directories and menus for the first 3 weeks.
- [ ] Write Factorial function using classes, providing implementation of call.
- [ ] Select your own Math function. Write it in Imperative and OOP form.

**Comment by kamyamah** [comment]
Group Project: Making Data Base for Mortensen 5/5
- Great Job Presenting had a clear plan and wire frame 2/2
- [ ] Organize files, directories and menus for the first 3 weeks. 1/1

- [ ] Write Factorial function using classes, providing implementation of call. 1/1

- [ ] Select your own Math function. Write it in Imperative and OOP form. 1/1
